# Generated by Django 5.2.13 on 2026-04-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
